### PR TITLE
Create footer

### LINKED ISSUE #23: Add a footer with basic contact information
- [ ] Email
- [ ] Address?
- [ ] Phone?
- [ ] Link to GitHub https://github.com/larucheio
- [ ] Link to Twitter? https://twitter.com/larucheio

### PR DESCRIPTION
**Pull request by rspt**
Fix #23

### CODE REVIEW

**Comment by rspt** [comment]
Is it better now?

**Comment by maxirozay** [comment]
I still find that there's a lot of margin.

**Comment by rspt** [comment]
I've reduced the spacing inside the footer.

The space before the footer is not related to this PR ;)

**Comment by maxirozay** [comment]
I like it like that :).

**Pull request merged**
