### PR TITLE
add process page

### PR DESCRIPTION
**Pull request by maxirozay**

### CODE REVIEW

**Comment by rspt** [comment]
I see that you've been inspired a lot by my index page and you shouldn't (it still has a lot of old things like an useless class or `p` inside `div`).

And I don't think this is a good idea to put the `main` tag at this place. It should rather be in the layout for single post. So you don't need to add the `main` tag to every *content* pages.

If you want to structure things correctly that's good but don't overthink it for now and write things from scratch; without any copy-pasting! Ask yourself if there's a meaning for every single tag you put in your HTML, if you don't have a more meaningful tag and if it's well structured.

**Comment by maxirozay** [comment]
We should't put the text in a p tag? And the div tag are to separate the left part and the right part.

**Comment by rspt** [comment]
I never say that you shouldn't put text inside `p` tags no?

And I think that there is more a meaningful way to split between two area than `div`; maybe `aside`.

**Comment by rspt** [comment]
Irrelevant due to PR #2

**Pull request closed without merging**
